### ISSUE TITLE
2 Raspberry Pico W(ifi)  one for  SPDIF RX    one for SPDIF TX

### ISSUE THREAD

**Issue by 4920441** [elehobica/pico_spdif_rx#14]
Hi,
Not an Issue but a project in my head which bothers me for quiet some time, but don't really now how to get there...

I'd like to build an endless SPDIF Extension cord via two wifi enabled RP2040 W Boards, So theoreically you could connect two spdif devices (source and target) anywhere in the house or even the world.

Your github page gave me sone hints, but nevertheless, I am kinda stuck on the Idea but have no idea how to make it work - and if it is able to work at all -   When there is too much jitter on a wifi link to beginn with, that would not work at all, I think...

Do you have any thoughts or hints about this topic?

Would be a absolutely cool if that worked simply by  a UDP Port where the receiving Pico  fires the data, the receiver buffers it and spits it out to its SPDIF TX.   - But is that too simple to work?

Cheers

**Comment by elehobica** [comment]
Hello.
If thinking about realizing it from the combination, it seems to come down to finding audio streaming RTP Tx and Rx which can run in Pico W.
If you get it, then try to tie spdif_rx with RTP Tx. and yes, the slight difference of sampling frequency should always problems between interface connections unless one side can be completely follow another. however, if compromising jitter or data, it should be basically feasible as done in spdif to i2s.
The same should be applied to RTP Rx and spdif_tx side as well for making the relay chain.
It could be quite general and nothing concrete steps yet, hope this helps you something.

Regards
