### ISSUE TITLE
assertion "!shared_state.playing_buffer0" failed

### ISSUE THREAD

**Issue by myreauks** [elehobica/pico_spdif_rx#6]
Hi!

First of all, thanks for the great work on this library. It makes yet another brilliant use case for rp2040.

I have successfully created the hardware to test your code out and managed to get the sample rate from my TV optical output to be recognized correctly with the detect sample rate example.

However, when trying the I2S output example, I get the following error:
```
Samp Freq = 48000 Hz (48.0015 KHz)
SPDIF C bits = 0x02000c04
Connecting PIO I2S audio
setting PIO freq for target sampling freq = 48000 Hz
System clock at 125000000 Hz, I2S clock divider 5208/256: PIO freq 6144393.0000 Hz
Copying stereo to stereo at 48000 Hz
Enabling PIO I2S audio (on core 0)
assertion "!shared_state.playing_buffer0" failed: file "/Users/user/pico/pico-examples/pico_spdif_rx/samples/lib/my_pico_audio_i2s/audio_i2s.c", line 548, function: audio_start_dma_transfer
```

I have no clue where to start looking for the solution for this problem. Any suggestions?

**Comment by elehobica** [comment]
Hi, myreauks.
It's my great pleasure that you have tried this library.
Thanks you for reporting this issue.
This is a bug, which happens only Debug mode.
I've applied the fix on main branch. Could you confirm if your error message is solved?

**Comment by myreauks** [comment]
Wow that was a fast reply!
This is great, I am getting I2s output to my DAC now. Thanks!
Next up is figuring out how to control volume with the commands that LGTV sends through the optical.
